### ISSUE TITLE
Cut/Copy/Paste???

### ISSUE THREAD

**Issue by randmor** [ganehag/serialterm#1]
I see there is a way to copy text out of SerialTerminal, but is there a way to paste text into SerialTerminal and have that text be sent on to the serial device on the end of your USB port?

I tried copying text from a text editor using Ctrl-C and can paste that text into another Chromebook app, so I know that part works. But when I try to paste into SerialTerm it does not seem to have that option. Ctrl-V doesn't work and right mouse click does not produce a pop-up command selection menu.

If there is a way, you need to make it more visible in the product, and I'd appreciate it if you could tell us the trick in this comment area. If there isn't a way, then I'd recommend this as a feature enhancement that may make you product usable by a wider market.

My application is to send MicroPython commands to an ESP9266 micro-controller attached via USB (/dev/ttyUSB). MicroPython's REPL mode has a "paste mode" where it will accept a block of MicroPython commands and execute them from the paste buffer. I want to use a Paste command on SerialTerminal running on a Chromebook because I can't get other MicroPython file transfer utilities like "ampy" or "mpy-upload" to work on Chromebook. If I can find a way of transferring source files to MicroPython, then I can use these ESP8266 boards in a micro-controller/IoT class where the school only has Chromebooks.

**Comment by ganehag** [comment]
Since it's a VT100 compatible terminal, CTRL+{KEY} usually represent a command. The key combination to get around this is CTRL+SHIFT+{KEY}.

So: 
Copy -> CTRL+ SHIFT+ C
PASTE -> CTRL + SHIFT + V

This is how it is handled in most VT100 terminals. But I can understand the confusion.

**Comment by randmor** [comment]
Thanks for the tip! 

    On Wednesday, May 24, 2017 5:41 AM, Mikael Ganehag Brorsson <notifications@github.com> wrote:
 

 Since it's a VT100 compatible terminal, CTRL+{KEY} usually represent a command. The key combination to get around this is CTRL+SHIFT+{KEY}.So:
Copy -> CTRL+ SHIFT+ C
PASTE -> CTRL + SHIFT + VThis is how it is handled in most VT100 terminals. But I can understand the confusion.—
